### ISSUE TITLE
General reading interface improvements

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-frontend#37]
- [x] Redo basic reading UI with basic ToC navigation. https://github.com/RebusFoundation/reader-frontend/issues/41
- [x] More full-featured default stylesheet for the reading content https://github.com/RebusFoundation/reader-frontend/issues/42
- [x] Chapter navigation: https://github.com/RebusFoundation/reader-frontend/issues/26

**Comment by baldurbjarnason** [comment]
I'm removing this from this week's milestone as I think this is more of a long term effort
