### ISSUE TITLE
Better server side processing of chapter markup

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-frontend#46]
- [x] Fetch them from storage instead of DB #47
- [x] Process with JSDOM #48
- [x] Sanitise with dompurify #49
- [x] Add hooks for annotation #50
